# Generated by Django 3.2.23 on 2023-12-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroomapp', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='Anon', max_length=255),
        ),
    ]
