# Generated by Django 3.2.23 on 2023-12-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushroomapp', '0010_alter_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
