# Generated by Django 3.2.23 on 2023-12-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushroomapp', '0011_remove_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-datetime']},
        ),
    ]
