# Generated by Django 3.2.23 on 2023-12-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroomapp', '0012_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['-datetime']},
        ),
        migrations.RemoveField(
            model_name='forum',
            name='user',
        ),
        migrations.AddField(
            model_name='forum',
            name='username',
            field=models.CharField(default='anon', max_length=255),
        ),
    ]
