# Generated by Django 3.2.23 on 2023-12-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroomapp', '0013_auto_20231210_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
